In [19]:
import pandas as pd

In [20]:
week1 = pd.read_csv("/home/gabrielajachs/Downloads/pandas/Restaurant - Week 1 Sales.csv")
pd.set_option('display.max_rows', 50000000)
week2 = pd.read_csv("/home/gabrielajachs/Downloads/pandas/Restaurant - Week 2 Sales.csv")
customers = pd.read_csv("/home/gabrielajachs/Downloads/pandas/Restaurant - Customers.csv")
foods = pd.read_csv("/home/gabrielajachs/Downloads/pandas/Restaurant - Foods.csv")

In [21]:
week1.head(3)

   Customer ID  Food ID
0          537        9
1           97        4
2          658        1

In [22]:
week2.head(3)

   Customer ID  Food ID
0          688       10
1          813        7
2          495       10

In [23]:
customers.head(3)

   ID First Name Last Name  Gender  Company                     Occupation
0   1     Joseph   Perkins    Male  Dynazzy  Community Outreach Specialist
1   2   Jennifer   Alvarez  Female     DabZ        Senior Quality Engineer
2   3      Roger     Black    Male  Tagfeed              Account Executive

In [24]:
foods.head(3)

   Food ID Food Item  Price
0        1     Sushi   3.99
1        2   Burrito   9.99
2        3      Taco   2.99

In [26]:
pd.concat(objs = [week1, week2], ignore_index = True)

     Customer ID  Food ID
0            537        9
1             97        4
2            658        1
3            202        2
4            155        9
5            213        8
6            600        1
7            503        5
8             71        3
9            174        3
10           961        9
11           966        5
12           641        4
13           288        2
14           149        4
15           954        2
16           147        9
17           155        1
18           550        6
19           101        7
20           549        6
21            75        6
22            78        7
23           514        5
24           833        7
25           329        8
26           586       10
27           341        1
28           519       10
29           680        9
30           419        7
31            20        1
32           822        6
33           226       10
34           203        2
35            77        1
36           628        4
37           296        9
38           821        9
39           697        8
40           264        7
41           477        9
42           524        4
43           121        3
44           290        7
45           100        1
46           260        6
47           798        9
48           462        3
49           896        7
50           953        1
51           682       10
52           809        7
53           450       10
54           772        7
55           304        3
56           159        6
57           189        4
58           876        2
59           864        8
60           799        8
61            68        6
62           812        8
63            30        2
64           921        2
65           941        6
66           108        3
67           315        4
68           358       10
69           249        9
70           491        9
71           110        8
72           737        3
73           836        6
74           749        9
75           758        8
76           527        3
77           677       10
78           741        3
79           540        3
80           433        7
81           250       10
82           504        1
83           819        4
84           910        7
85           351       10
86           282        7
87           117        5
88           937       10
89            63        6
90           144        2
91           393        7
92           380        7
93           515        7
94           233        3
95           357        3
96             3        2
97           875        2
98           352        6
99            93        3
100          323        1
101           21        4
102           64       10
103          912       10
104          327        6
105          399        2
106          459        6
107          418        7
108          669        3
109          259        9
110          816        7
111          761        9
112          410        7
113          304        2
114          772       10
115           80        2
116          363        9
117          504        5
118          728        6
119           71        8
120          479        6
121          922        1
122          244        2
123          319        9
124          909        1
125          919       10
126           51        2
127           26        9
128          472        8
129           77        9
130          608        6
131          160        5
132          645        8
133          574       10
134          374        4
135          100        7
136          762        8
137           45        7
138          332        7
139          338       10
140          140        8
141          567        2
142          602        1
143           10        2
144           77        2
145           74        1
146         1000        2
147          529        7
148          881        5
149          673        7
150          107        2
151          876        8
152          703        1
153          225       10
154          962        1
155          114        5
156          250        7
157          346        4
158          191        2
159          331        2
160          310        2
161          738        9
162          427        7
163          331        5
164          902        6
165          867        9
166          385        5
167          555        9
168           67        7
169          138        4
170          775        5
171          833        3
172          648        5
173          475       10
174          483        6
175          968        1
176          203        3
177          313        9
178          263        8
179          871        5
180          747        5
181           38        4
182          190        9
183          348        6
184          226        3
185          167        9
186          671        8
187          190        1
188          909        4
189          501        6
190          406        2
191           47        8
192          482        3
193          163        1
194          991        2
195          539        6
196           53        2
197           51       10
198          348        9
199          321        1
200          493        9
201          650        9
202          310        1
203          848        6
204          307        9
205          798        1
206          606        7
207          100        4
208          783        6
209          985        5
210          123        6
211          809       10
212           21        4
213          764        9
214           92        1
215          386        6
216          331        3
217           62        5
218           91        8
219          368        6
220          147        8
221          745        4
222          184        3
223          828        8
224          578        5
225          491        4
226           62        4
227           77        9
228          506        9
229          271        9
230          584       10
231          148        5
232          595        3
233          274       10
234          646        1
235          520        8
236          644        8
237          725        8
238          934        4
239          151       10
240          945        5
241          343        3
242          380        9
243          911        4
244          621        9
245          413        9
246          926        6
247          134        3
248          396        6
249          535       10
250          688       10
251          813        7
252          495       10
253          189        5
254          267        3
255          310        5
256          761        2
257          443        5
258          729        9
259          741        8
260          847        6
261          156       10
262          550        7
263          620       10
264          272        4
265          511        2
266            8        6
267          534        7
268          909        6
269          732        9
270          372        4
271          713        1
272          496        3
273          381        9
274           13        2
275          101        4
276          325        7
277          674        2
278          564        8
279          578        5
280           21        4
281          755        7
282          509        7
283          639        2
284          170        2
285          668        3
286          321        3
287          629        2
288          767        6
289          799        7
290          253        8
291          473        1
292          537        5
293          343        5
294          761        3
295          922        1
296          780        6
297          198       10
298          937       10
299          479        3
300          706        7
301          281        6
302          726        7
303          343        2
304          277        3
305          969        3
306          543        4
307          275        8
308          787        7
309          424        4
310          612        6
311          379        9
312          647        1
313          942        3
314          528       10
315          673        4
316          853        3
317          111        3
318          736        8
319          503        8
320          445        6
321          580       10
322          670        6
323          359        6
324          132        8
325          819        5
326          829        6
327          928       10
328          592        5
329          163       10
330          694        7
331           98        5
332          791        2
333          398        5
334          709        4
335           56        3
336          397        1
337          239        6
338          304        3
339          893        3
340          581        1
341          693        3
342          827        4
343          815        6
344          574        9
345          752       10
346          596        8
347          489        9
348          792        4
349          861        1
350          303        9
351          548        9
352          517        2
353          784        6
354          621        6
355          529       10
356          204       10
357          136        1
358          994        2
359          186        3
360          253        7
361          859        7
362          496        8
363          423        2
364          211        4
365          884        7
366           81       10
367          437       10
368          526        1
369          951        5
370          508        4
371          236        5
372          127        1
373          198        7
374          877       10
375          816        2
376          666        9
377          415        5
378           24        8
379          720        1
380          240        2
381          919        8
382          459        1
383          938       10
384           46        6
385          458        9
386          630        6
387           75        4
388          287        5
389          927        4
390          522        8
391          805        8
392          365        6
393          257        1
394          957       10
395          692        4
396          547       10
397          798        5
398          913        2
399           35        8
400          968        4
401          222       10
402          122        2
403           73        8
404          653        9
405          937        2
406          171        2
407          193        2
408          668        9
409          996       10
410          222       10
411           70        2
412           77        7
413          743        8
414          589        4
415          867       10
416          831        4
417          905        1
418          977        7
419          746       10
420          922        2
421          866        9
422          746       10
423          495        6
424          486        6
425           55        9
426          312        2
427          604        3
428          122       10
429          936        9
430          503        9
431          628        7
432           55        4
433          858        5
434          175        6
435          530        7
436          850       10
437          681       10
438          750        6
439          578        5
440          287        8
441           39       10
442          458        3
443           30        4
444          827       10
445          462        8
446          361        6
447           27        4
448          234        1
449          570        8
450          751        2
451          463       10
452          253        5
453          633        1
454          622        9
455          959        4
456          810        2
457           80        4
458          155        3
459          488        2
460          482        1
461          495        2
462          188        8
463          861        5
464          305        2
465          869        7
466          131        1
467          520        7
468          208        4
469          145        5
470          495        2
471          794        6
472          734       10
473          540        3
474          735        2
475          940        8
476          571        7
477          888        2
478          664        6
479          343        7
480          143        4
481          505        3
482           54        8
483          959        2
484          367        8
485          883        8
486          251        9
487          855        4
488          233        3
489          559       10
490          734        1
491          677        3
492          276        4
493           45        8
494          945        4
495          783       10
496          556       10
497          547        9
498          252        9
499          249        6

In [28]:
sales = pd.concat(objs = [week1, week2], keys = ["Week 1","Week 2"])

In [29]:
sales.head(3)

          Customer ID  Food ID
Week 1 0          537        9
       1           97        4
       2          658        1

In [31]:
week1[week1["Customer ID"] == 155]

    Customer ID  Food ID
4           155        9
17          155        1

In [32]:
week2[week2["Customer ID"] == 155]

     Customer ID  Food ID
208          155        3

In [34]:
week1.merge(week2, how = "inner", on = "Customer ID", suffixes = [" - Week 1", " - Week 2"])

    Customer ID  Food ID - Week 1  Food ID - Week 2
0           537                 9                 5
1           155                 9                 3
2           155                 1                 3
3           503                 5                 8
4           503                 5                 9
5           550                 6                 7
6           101                 7                 4
7            75                 6                 4
8            77                 1                 7
9            77                 9                 7
10           77                 2                 7
11           77                 9                 7
12          628                 4                 7
13          798                 9                 5
14          798                 1                 5
15          462                 3                 8
16          304                 3                 3
17          304                 2                 3
18          189                 4                 5
19          799                 8                 7
20           30                 2                 4
21          249                 9                 6
22          677                10                 3
23          741                 3                 8
24          540                 3                 3
25          819                 4                 5
26          937                10                10
27          937                10                 2
28          233                 3                 3
29           21                 4                 4
30           21                 4                 4
31          459                 6                 1
32          816                 7                 2
33          761                 9                 2
34          761                 9                 3
35           80                 2                 4
36          479                 6                 3
37          922                 1                 1
38          922                 1                 2
39          909                 1                 6
40          909                 4                 6
41          919                10                 8
42          574                10                 9
43           45                 7                 8
44          529                 7                10
45          673                 7                 4
46          310                 2                 5
47          310                 1                 5
48          867                 9                10
49          968                 1                 4
50          482                 3                 1
51          163                 1                10
52          321                 1                 3
53          783                 6                10
54          578                 5                 5
55          578                 5                 5
56          520                 8                 7
57          945                 5                 4
58          343                 3                 5
59          343                 3                 2
60          343                 3                 7
61          621                 9                 6

In [35]:
week1.merge(week2, how = "inner", on = ["Customer ID", "Food ID"])

   Customer ID  Food ID
0          304        3
1          540        3
2          937       10
3          233        3
4           21        4
5           21        4
6          922        1
7          578        5
8          578        5

In [45]:
merged = week1.merge(week2, how = "outer", on = "Customer ID", suffixes = [" - Week 1", " - Week 2"],
           indicator = True)

In [46]:
merged["_merge"].value_counts()

right_only    197
left_only     195
both           62
Name: _merge, dtype: int64

In [47]:
mask = merged["_merge"].isin(["right_only", "left_only"])
merged[mask]

     Customer ID  Food ID - Week 1  Food ID - Week 2      _merge
1             97               4.0               NaN   left_only
2            658               1.0               NaN   left_only
3            202               2.0               NaN   left_only
6            213               8.0               NaN   left_only
7            600               1.0               NaN   left_only
10            71               3.0               NaN   left_only
11            71               8.0               NaN   left_only
12           174               3.0               NaN   left_only
13           961               9.0               NaN   left_only
14           966               5.0               NaN   left_only
15           641               4.0               NaN   left_only
16           288               2.0               NaN   left_only
17           149               4.0               NaN   left_only
18           954               2.0               NaN   left_only
19           147               9.0               NaN   left_only
20           147               8.0               NaN   left_only
23           549               6.0               NaN   left_only
25            78               7.0               NaN   left_only
26           514               5.0               NaN   left_only
27           833               7.0               NaN   left_only
28           833               3.0               NaN   left_only
29           329               8.0               NaN   left_only
30           586              10.0               NaN   left_only
31           341               1.0               NaN   left_only
32           519              10.0               NaN   left_only
33           680               9.0               NaN   left_only
34           419               7.0               NaN   left_only
35            20               1.0               NaN   left_only
36           822               6.0               NaN   left_only
37           226              10.0               NaN   left_only
38           226               3.0               NaN   left_only
39           203               2.0               NaN   left_only
40           203               3.0               NaN   left_only
46           296               9.0               NaN   left_only
47           821               9.0               NaN   left_only
48           697               8.0               NaN   left_only
49           264               7.0               NaN   left_only
50           477               9.0               NaN   left_only
51           524               4.0               NaN   left_only
52           121               3.0               NaN   left_only
53           290               7.0               NaN   left_only
54           100               1.0               NaN   left_only
55           100               7.0               NaN   left_only
56           100               4.0               NaN   left_only
57           260               6.0               NaN   left_only
61           896               7.0               NaN   left_only
62           953               1.0               NaN   left_only
63           682              10.0               NaN   left_only
64           809               7.0               NaN   left_only
65           809              10.0               NaN   left_only
66           450              10.0               NaN   left_only
67           772               7.0               NaN   left_only
68           772              10.0               NaN   left_only
71           159               6.0               NaN   left_only
73           876               2.0               NaN   left_only
74           876               8.0               NaN   left_only
75           864               8.0               NaN   left_only
77            68               6.0               NaN   left_only
78           812               8.0               NaN   left_only
80           921               2.0               NaN   left_only
81           941               6.0               NaN   left_only
82           108               3.0               NaN   left_only
83           315               4.0               NaN   left_only
84           358              10.0               NaN   left_only
86           491               9.0               NaN   left_only
87           491               4.0               NaN   left_only
88           110               8.0               NaN   left_only
89           737               3.0               NaN   left_only
90           836               6.0               NaN   left_only
91           749               9.0               NaN   left_only
92           758               8.0               NaN   left_only
93           527               3.0               NaN   left_only
97           433               7.0               NaN   left_only
98           250              10.0               NaN   left_only
99           250               7.0               NaN   left_only
100          504               1.0               NaN   left_only
101          504               5.0               NaN   left_only
103          910               7.0               NaN   left_only
104          351              10.0               NaN   left_only
105          282               7.0               NaN   left_only
106          117               5.0               NaN   left_only
109           63               6.0               NaN   left_only
110          144               2.0               NaN   left_only
111          393               7.0               NaN   left_only
112          380               7.0               NaN   left_only
113          380               9.0               NaN   left_only
114          515               7.0               NaN   left_only
116          357               3.0               NaN   left_only
117            3               2.0               NaN   left_only
118          875               2.0               NaN   left_only
119          352               6.0               NaN   left_only
120           93               3.0               NaN   left_only
121          323               1.0               NaN   left_only
124           64              10.0               NaN   left_only
125          912              10.0               NaN   left_only
126          327               6.0               NaN   left_only
127          399               2.0               NaN   left_only
129          418               7.0               NaN   left_only
130          669               3.0               NaN   left_only
131          259               9.0               NaN   left_only
135          410               7.0               NaN   left_only
137          363               9.0               NaN   left_only
138          728               6.0               NaN   left_only
142          244               2.0               NaN   left_only
143          319               9.0               NaN   left_only
147           51               2.0               NaN   left_only
148           51              10.0               NaN   left_only
149           26               9.0               NaN   left_only
150          472               8.0               NaN   left_only
151          608               6.0               NaN   left_only
152          160               5.0               NaN   left_only
153          645               8.0               NaN   left_only
155          374               4.0               NaN   left_only
156          762               8.0               NaN   left_only
158          332               7.0               NaN   left_only
159          338              10.0               NaN   left_only
160          140               8.0               NaN   left_only
161          567               2.0               NaN   left_only
162          602               1.0               NaN   left_only
163           10               2.0               NaN   left_only
164           74               1.0               NaN   left_only
165         1000               2.0               NaN   left_only
167          881               5.0               NaN   left_only
169          107               2.0               NaN   left_only
170          703               1.0               NaN   left_only
171          225              10.0               NaN   left_only
172          962               1.0               NaN   left_only
173          114               5.0               NaN   left_only
174          346               4.0               NaN   left_only
175          191               2.0               NaN   left_only
176          331               2.0               NaN   left_only
177          331               5.0               NaN   left_only
178          331               3.0               NaN   left_only
181          738               9.0               NaN   left_only
182          427               7.0               NaN   left_only
183          902               6.0               NaN   left_only
185          385               5.0               NaN   left_only
186          555               9.0               NaN   left_only
187           67               7.0               NaN   left_only
188          138               4.0               NaN   left_only
189          775               5.0               NaN   left_only
190          648               5.0               NaN   left_only
191          475              10.0               NaN   left_only
192          483               6.0               NaN   left_only
194          313               9.0               NaN   left_only
195          263               8.0               NaN   left_only
196          871               5.0               NaN   left_only
197          747               5.0               NaN   left_only
198           38               4.0               NaN   left_only
199          190               9.0               NaN   left_only
200          190               1.0               NaN   left_only
201          348               6.0               NaN   left_only
202          348               9.0               NaN   left_only
203          167               9.0               NaN   left_only
204          671               8.0               NaN   left_only
205          501               6.0               NaN   left_only
206          406               2.0               NaN   left_only
207           47               8.0               NaN   left_only
210          991               2.0               NaN   left_only
211          539               6.0               NaN   left_only
212           53               2.0               NaN   left_only
214          493               9.0               NaN   left_only
215          650               9.0               NaN   left_only
216          848               6.0               NaN   left_only
217          307               9.0               NaN   left_only
218          606               7.0               NaN   left_only
220          985               5.0               NaN   left_only
221          123               6.0               NaN   left_only
222          764               9.0               NaN   left_only
223           92               1.0               NaN   left_only
224          386               6.0               NaN   left_only
225           62               5.0               NaN   left_only
226           62               4.0               NaN   left_only
227           91               8.0               NaN   left_only
228          368               6.0               NaN   left_only
229          745               4.0               NaN   left_only
230          184               3.0               NaN   left_only
231          828               8.0               NaN   left_only
234          506               9.0               NaN   left_only
235          271               9.0               NaN   left_only
236          584              10.0               NaN   left_only
237          148               5.0               NaN   left_only
238          595               3.0               NaN   left_only
239          274              10.0               NaN   left_only
240          646               1.0               NaN   left_only
242          644               8.0               NaN   left_only
243          725               8.0               NaN   left_only
244          934               4.0               NaN   left_only
245          151              10.0               NaN   left_only
250          911               4.0               NaN   left_only
252          413               9.0               NaN   left_only
253          926               6.0               NaN   left_only
254          134               3.0               NaN   left_only
255          396               6.0               NaN   left_only
256          535              10.0               NaN   left_only
257          688               NaN              10.0  right_only
258          813               NaN               7.0  right_only
259          495               NaN              10.0  right_only
260          495               NaN               6.0  right_only
261          495               NaN               2.0  right_only
262          495               NaN               2.0  right_only
263          267               NaN               3.0  right_only
264          443               NaN               5.0  right_only
265          729               NaN               9.0  right_only
266          847               NaN               6.0  right_only
267          156               NaN              10.0  right_only
268          620               NaN              10.0  right_only
269          272               NaN               4.0  right_only
270          511               NaN               2.0  right_only
271            8               NaN               6.0  right_only
272          534               NaN               7.0  right_only
273          732               NaN               9.0  right_only
274          372               NaN               4.0  right_only
275          713               NaN               1.0  right_only
276          496               NaN               3.0  right_only
277          496               NaN               8.0  right_only
278          381               NaN               9.0  right_only
279           13               NaN               2.0  right_only
280          325               NaN               7.0  right_only
281          674               NaN               2.0  right_only
282          564               NaN               8.0  right_only
283          755               NaN               7.0  right_only
284          509               NaN               7.0  right_only
285          639               NaN               2.0  right_only
286          170               NaN               2.0  right_only
287          668               NaN               3.0  right_only
288          668               NaN               9.0  right_only
289          629               NaN               2.0  right_only
290          767               NaN               6.0  right_only
291          253               NaN               8.0  right_only
292          253               NaN               7.0  right_only
293          253               NaN               5.0  right_only
294          473               NaN               1.0  right_only
295          780               NaN               6.0  right_only
296          198               NaN              10.0  right_only
297          198               NaN               7.0  right_only
298          706               NaN               7.0  right_only
299          281               NaN               6.0  right_only
300          726               NaN               7.0  right_only
301          277               NaN               3.0  right_only
302          969               NaN               3.0  right_only
303          543               NaN               4.0  right_only
304          275               NaN               8.0  right_only
305          787               NaN               7.0  right_only
306          424               NaN               4.0  right_only
307          612               NaN               6.0  right_only
308          379               NaN               9.0  right_only
309          647               NaN               1.0  right_only
310          942               NaN               3.0  right_only
311          528               NaN              10.0  right_only
312          853               NaN               3.0  right_only
313          111               NaN               3.0  right_only
314          736               NaN               8.0  right_only
315          445               NaN               6.0  right_only
316          580               NaN              10.0  right_only
317          670               NaN               6.0  right_only
318          359               NaN               6.0  right_only
319          132               NaN               8.0  right_only
320          829               NaN               6.0  right_only
321          928               NaN              10.0  right_only
322          592               NaN               5.0  right_only
323          694               NaN               7.0  right_only
324           98               NaN               5.0  right_only
325          791               NaN               2.0  right_only
326          398               NaN               5.0  right_only
327          709               NaN               4.0  right_only
328           56               NaN               3.0  right_only
329          397               NaN               1.0  right_only
330          239               NaN               6.0  right_only
331          893               NaN               3.0  right_only
332          581               NaN               1.0  right_only
333          693               NaN               3.0  right_only
334          827               NaN               4.0  right_only
335          827               NaN              10.0  right_only
336          815               NaN               6.0  right_only
337          752               NaN              10.0  right_only
338          596               NaN               8.0  right_only
339          489               NaN               9.0  right_only
340          792               NaN               4.0  right_only
341          861               NaN               1.0  right_only
342          861               NaN               5.0  right_only
343          303               NaN               9.0  right_only
344          548               NaN               9.0  right_only
345          517               NaN               2.0  right_only
346          784               NaN               6.0  right_only
347          204               NaN              10.0  right_only
348          136               NaN               1.0  right_only
349          994               NaN               2.0  right_only
350          186               NaN               3.0  right_only
351          859               NaN               7.0  right_only
352          423               NaN               2.0  right_only
353          211               NaN               4.0  right_only
354          884               NaN               7.0  right_only
355           81               NaN              10.0  right_only
356          437               NaN              10.0  right_only
357          526               NaN               1.0  right_only
358          951               NaN               5.0  right_only
359          508               NaN               4.0  right_only
360          236               NaN               5.0  right_only
361          127               NaN               1.0  right_only
362          877               NaN              10.0  right_only
363          666               NaN               9.0  right_only
364          415               NaN               5.0  right_only
365           24               NaN               8.0  right_only
366          720               NaN               1.0  right_only
367          240               NaN               2.0  right_only

In [50]:
week1 = week1.merge(foods, how = "left", on = "Food ID", sort = True)
week1.head()

   Customer ID  Food ID Food Item  Price
0          658        1     Sushi   3.99
1          600        1     Sushi   3.99
2          155        1     Sushi   3.99
3          341        1     Sushi   3.99
4           20        1     Sushi   3.99

In [51]:
week1 = pd.read_csv("/home/gabrielajachs/Downloads/pandas/Restaurant - Week 1 Sales.csv")
pd.set_option('display.max_rows', 50000000)
week2 = pd.read_csv("/home/gabrielajachs/Downloads/pandas/Restaurant - Week 2 Sales.csv")
customers = pd.read_csv("/home/gabrielajachs/Downloads/pandas/Restaurant - Customers.csv")
foods = pd.read_csv("/home/gabrielajachs/Downloads/pandas/Restaurant - Foods.csv")

In [52]:
week2.head()

   Customer ID  Food ID
0          688       10
1          813        7
2          495       10
3          189        5
4          267        3

In [53]:
customers.head()

   ID First Name Last Name  Gender  Company                     Occupation
0   1     Joseph   Perkins    Male  Dynazzy  Community Outreach Specialist
1   2   Jennifer   Alvarez  Female     DabZ        Senior Quality Engineer
2   3      Roger     Black    Male  Tagfeed              Account Executive
3   4     Steven     Evans    Male     Fatz               Registered Nurse
4   5       Judy  Morrison  Female  Demivee                Legal Assistant

In [54]:
week2.merge(customers, how = "left", left_on = "Customer ID", right_on = "ID", sort = True).drop("ID", axis = "columns")

,Customer ID,Food ID,First Name,Last Name,Gender,Company,Occupation
0,8,6,Frances,Adams,Female,Dabshots,Developer III
1,13,2,Ruth,Alvarez,Female,Twitterlist,Mechanical Systems Engineer
2,21,4,Albert,Burns,Male,Rhynoodle,Junior Executive
3,24,8,Donna,Thomas,Female,Jaxbean,Chief Design Engineer
4,27,4,Jessica,Bennett,Female,Twitternation,Account Executive
5,30,4,Pamela,Hicks,Female,Ntags,Cost Accountant
6,35,8,Nicole,Chapman,Female,Pixonyx,Electrical Engineer
7,39,10,Teresa,Harrison,Female,Oba,Payment Adjustment Coordinator
8,45,8,Earl,Marshall,Male,Agivu,Dental Hygienist
9,46,6,Adam,Cole,Male,Trupe,Accountant III
10,54,8,Amanda,Berry,Female,Jaxspan,Automation Specialist III
11,55,9,Ralph,Ford,Male,Browsezoom,Safety Technician IV
12,55,4,Ralph,Ford,Male,Browsezoom,Safety Technician IV
13,56,3,Anne,Berry,Female,Twinder,VP Sales
14,70,2,Michelle,Bowman,Female,Gabvine,VP Marketing
15,73,8,Kenneth,Miller,Male,Vimbo,Senior Editor
16,75,4,Catherine,Carpenter,Female,Zoozzy,Marketing Manager
17,77,7,Lori,Edwards,Female,Dabvine,Sales Representative
18,80,4,George,Mason,Male,Jaxworks,Engineer I
19,81,10,Mildred,Fowler,Female,Fivechat,Operator
20,98,5,Jean,Mills,Female,Fivebridge,Product Engineer
21,101,4,Jeremy,Nelson,Male,Brainlounge,Web Developer IV
22,111,3,Patrick,Morrison,Male,Eimbee,Mechanical Systems Engineer
23,122,2,Martin,Hawkins,Male,Centizu,Assistant Manager
24,122,10,Martin,Hawkins,Male,Centizu,Assistant Manager
25,127,1,Jesse,Henderson,Male,Eabox,Environmental Tech
26,131,1,Margaret,Porter,Female,Eazzy,Sales Associate
27,132,8,Judith,Perez,Female,Jaxworks,Structural Engineer
28,136,1,Clarence,Fox,Male,Devshare,Graphic Designer
29,143,4,Christopher,Long,Male,Mybuzz,Accounting Assistant III
30,145,5,Doris,Wagner,Female,Browsezoom,Graphic Designer
31,155,3,Carolyn,Diaz,Female,Gigazoom,Database Administrator III
32,156,10,Stephanie,Kelly,Female,Youopia,Automation Specialist III
33,163,10,Lisa,Palmer,Female,Shufflebeat,Food Chemist
34,170,2,Juan,Fields,Male,Voomm,Safety Technician IV
35,171,2,Julie,Pierce,Female,Eazzy,Systems Administrator IV
36,175,6,Ralph,White,Male,Muxo,Staff Accountant IV
37,186,3,Norma,Johnson,Female,Fiveclub,Operator
38,188,8,Earl,Parker,Male,Gigazoom,Nurse
39,189,5,Roger,Gordon,Male,Skilith,Operator
40,193,2,Melissa,Kelley,Female,Cogilith,Paralegal
41,198,10,Gary,Russell,Male,Bubblebox,Software Test Engineer I
42,198,7,Gary,Russell,Male,Bubblebox,Software Test Engineer I
43,204,10,Daniel,Moreno,Male,Ntag,Registered Nurse
44,208,4,Bonnie,Rice,Female,Eamia,Cost Accountant
45,211,4,Emily,West,Female,Eimbee,Automation Specialist II
46,222,10,Larry,Riley,Male,Aivee,Cost Accountant
47,222,10,Larry,Riley,Male,Aivee,Cost Accountant
48,233,3,Robin,Lopez,Female,Wordpedia,Editor
49,234,1,Helen,Wallace,Female,Bubblebox,Financial Analyst
50,236,5,Christine,Lewis,Female,Oyoyo,Engineer IV
51,239,6,James,Carter,Male,Rhybox,Software Engineer II
52,240,2,Diane,Rogers,Female,Voonix,Librarian
53,249,6,Anthony,Carpenter,Male,Shuffletag,Health Coach I
54,251,9,Joseph,Anderson,Male,Quinu,Administrative Officer
55,252,9,Douglas,Powell,Male,Jetwire,Geologist IV
56,253,8,Amy,Lawson,Female,Browseblab,Compensation Analyst
57,253,7,Amy,Lawson,Female,Browseblab,Compensation Analyst
58,253,5,Amy,Lawson,Female,Browseblab,Compensation Analyst
59,257,1,Albert,Scott,Male,Gigashots,Senior Quality Engineer
60,267,3,Matthew,Wood,Male,Agimba,Product Engineer
61,272,4,Jacqueline,Olson,Female,Gigashots,Director of Sales
62,275,8,Denise,Green,Female,Trunyx,Software Test Engineer IV
63,276,4,Kimberly,Olson,Female,Voonyx,Occupational Therapist
64,277,3,Carol,Gilbert,Female,Nlounge,VP Marketing
65,281,6,Amanda,Butler,Female,Skyble,Research Assistant IV
66,287,5,Sandra,Holmes,Female,Ailane,Civil Engineer
67,287,8,Sandra,Holmes,Female,Ailane,Civil Engineer
68,303,9,Ernest,Davis,Male,Zava,Administrative Officer
69,304,3,Margaret,Cruz,Female,Jaxnation,Automation Specialist III
70,305,2,Shawn,Porter,Male,Twinder,Payment Adjustment Coordinator
71,310,5,Bobby,Sims,Male,Skynoodle,Marketing Manager
72,312,2,Debra,Banks,Female,Voonder,Cost Accountant
73,321,3,Beverly,Fuller,Female,Gabcube,Engineer II
74,325,7,Evelyn,Powell,Female,Gabtype,Senior Developer
75,343,5,Joe,Price,Male,Fanoodle,Marketing Manager
76,343,2,Joe,Price,Male,Fanoodle,Marketing Manager
77,343,7,Joe,Price,Male,Fanoodle,Marketing Manager
78,359,6,Ruth,Kim,Female,Tazz,Research Assistant I
79,361,6,Russell,Nguyen,Male,Kazio,Administrative Assistant II
80,365,6,Russell,Garza,Male,Yadel,Actuary
81,367,8,Mildred,Carr,Female,Jabberbean,Account Executive
82,372,4,Steve,Robinson,Male,Zoomlounge,Dental Hygienist
83,379,9,Adam,West,Male,Edgewire,Actuary
84,381,9,Charles,Torres,Male,Tazzy,Food Chemist
85,397,1,Brenda,Ryan,Female,Oozz,Nurse Practicioner
86,398,5,Victor,Hall,Male,Youspan,Senior Developer
87,415,5,Jimmy,Bradley,Male,Twinte,Design Engineer
88,423,2,Carl,Kim,Male,Trupe,Help Desk Technician
89,424,4,Anthony,Patterson,Male,Yata,Senior Developer
90,437,10,Rose,Mccoy,Female,Tagtune,Quality Control Specialist
91,443,5,Robert,Thompson,Male,Oozz,Teacher
92,445,6,Mark,Butler,Male,Quatz,Editor
93,458,9,Peter,Brooks,Male,Gabtune,Programmer II
94,458,3,Peter,Brooks,Male,Gabtune,Programmer II
95,459,1,James,Williamson,Male,Edgeify,Geological Engineer
96,462,8,Anne,Lopez,Female,Mydo,Mechanical Systems Engineer
97,463,10,Kelly,Johnston,Female,Jayo,Administrative Assistant I
98,473,1,Marilyn,Morrison,Female,Thoughtbeat,Human Resources Manager
99,479,3,Juan,Campbell,Male,Wikizz,VP Quality Control
100,482,1,Cheryl,Hunt,Female,Linklinks,Senior Developer
101,486,6,Janet,Bowman,Female,Edgetag,Safety Technician II
102,488,2,Marie,Burke,Female,Realblab,Internal Auditor
103,489,9,Julie,Reed,Female,Flipbug,Junior Executive
104,495,10,Deborah,Little,Female,Babbleblab,VP Accounting
105,495,6,Deborah,Little,Female,Babbleblab,VP Accounting
106,495,2,Deborah,Little,Female,Babbleblab,VP Accounting
107,495,2,Deborah,Little,Female,Babbleblab,VP Accounting
108,496,3,Brian,Murray,Male,Abatz,Senior Sales Associate
109,496,8,Brian,Murray,Male,Abatz,Senior Sales Associate
110,503,8,Justin,Daniels,Male,Oloo,Environmental Tech
111,503,9,Justin,Daniels,Male,Oloo,Environmental Tech
112,505,3,Douglas,Edwards,Male,Jabbersphere,Recruiting Manager
113,508,4,Louise,Andrews,Female,Dabtype,Compensation Analyst
114,509,7,Tammy,Cole,Female,Trunyx,Librarian
115,511,2,Phyllis,Morgan,Female,Eimbee,Environmental Specialist
116,517,2,Justin,Edwards,Male,Tazz,Analyst Programmer
117,520,7,Melissa,Wallace,Female,Skyvu,Administrative Officer
118,522,8,Lisa,Williams,Female,Zoonder,Operator
119,526,1,John,Lynch,Male,Avamm,Programmer I
120,528,10,Andrea,Patterson,Female,Dynabox,Account Executive
121,529,10,Kathy,Rogers,Female,Yabox,Sales Representative
122,530,7,Donald,Morales,Male,Blogpad,Financial Analyst
123,534,7,Carl,Butler,Male,Npath,Office Assistant I
124,537,5,Cheryl,Carroll,Female,Zoombeat,Registered Nurse
125,540,3,Jessica,Hicks,Female,Cogibox,Structural Analysis Engineer
126,543,4,Robert,Martin,Male,Tavu,Community Outreach Specialist
127,547,10,Tina,Watkins,Female,Thoughtstorm,Accountant II
128,547,9,Tina,Watkins,Female,Thoughtstorm,Accountant II
129,548,9,Andrea,Butler,Female,Dabtype,Human Resources Manager
130,550,7,Walter,Miller,Male,Yata,Payment Adjustment Coordinator
131,556,10,Samuel,Bailey,Male,Oyoloo,Nurse
132,559,10,Jeffrey,Henry,Male,Brightdog,Environmental Tech
133,564,8,Timothy,Bowman,Male,Oloo,Director of Sales
134,570,8,Steven,Rose,Male,Npath,Sales Representative
135,571,7,David,Collins,Male,Midel,Assistant Professor
136,574,9,Lisa,Stone,Female,Riffpedia,Senior Editor
137,578,5,Donald,Matthews,Male,Fiveclub,Physical Therapy Assistant
138,578,5,Donald,Matthews,Male,Fiveclub,Physical Therapy Assistant
139,580,10,Kimberly,Morris,Female,Photospace,Assistant Media Planner
140,581,1,Anthony,Mcdonald,Male,Wikido,Help Desk Operator
141,589,4,Matthew,Reyes,Male,Eabox,Engineer I
142,592,5,Alan,Banks,Male,Fiveclub,Recruiting Manager
143,596,8,Eric,Schmidt,Male,Meembee,VP Quality Control
144,604,3,Jacqueline,Olson,Female,Podcat,Structural Engineer
145,612,6,Ann,Campbell,Female,Brainlounge,Staff Accountant IV
146,620,10,Anne,Hill,Female,Dabshots,Recruiter
147,621,6,Amy,Long,Female,Skidoo,Research Associate
148,622,9,Jennifer,Dixon,Female,Tagfeed,Analyst Programmer
149,628,7,David,Gardner,Male,Jetwire,Software Consultant
150,629,2,Lillian,Alvarez,Female,Ntag,Human Resources Assistant III
151,630,6,Randy,Henderson,Male,Tagpad,Design Engineer
152,633,1,Howard,Wallace,Male,Livefish,Associate Professor
153,639,2,Gerald,Bradley,Male,Fatz,Assistant Professor
154,647,1,Brenda,Duncan,Female,Leenti,Administrative Officer
155,653,9,Randy,Foster,Male,Dabshots,Senior Editor
156,664,6,Donna,Butler,Female,Miboo,Community Outreach Specialist
157,666,9,Jessica,Lawson,Female,Lazzy,Environmental Specialist
158,668,3,Diana,Bryant,Female,Jabbersphere,Pharmacist
159,668,9,Diana,Bryant,Female,Jabbersphere,Pharmacist
160,670,6,Christina,Webb,Female,Riffwire,Project Manager
161,673,4,John,Pierce,Male,Trudoo,Web Developer II
162,674,2,Brenda,Gonzales,Female,Jabbersphere,Safety Technician III
163,677,3,Richard,Martin,Male,Gabtype,Analog Circuit Design manager
164,681,10,Janice,Pierce,Female,Skimia,Structural Analysis Engineer
165,688,10,Carl,Williamson,Male,Thoughtmix,Graphic Designer
166,692,4,Kenneth,Brooks,Male,Mycat,Associate Professor
167,693,3,Wayne,Patterson,Male,Thoughtstorm,Research Assistant III
168,694,7,Frances,Lynch,Female,Topicware,General Manager
169,706,7,Paul,Harvey,Male,Buzzster,Graphic Designer
170,709,4,Joseph,Taylor,Male,Babbleopia,Geological Engineer
171,713,1,Kenneth,Schmidt,Male,Skyble,Financial Analyst
172,720,1,Earl,George,Male,Talane,Design Engineer
173,726,7,Deborah,Cook,Female,Flashdog,Geologist IV
174,729,9,Roger,Lawrence,Male,Wikizz,Web Designer I
175,732,9,Daniel,Grant,Male,Riffpath,Nurse Practicioner
176,734,10,Robin,Thomas,Female,Izio,Account Coordinator
177,734,1,Robin,Thomas,Female,Izio,Account Coordinator
178,735,2,Eugene,Elliott,Male,Meedoo,VP Marketing
179,736,8,Bobby,Hayes,Male,Centimia,Social Worker
180,741,8,Diana,Welch,Female,Eayo,Occupational Therapist
181,743,8,Harold,Mills,Male,Zoomzone,Marketing Assistant
182,746,10,Karen,Hernandez,Female,Devcast,Financial Analyst
183,746,10,Karen,Hernandez,Female,Devcast,Financial Analyst
184,750,6,Matthew,Boyd,Male,InnoZ,Chief Design Engineer
185,751,2,Walter,Clark,Male,Brightdog,Software Engineer III
186,752,10,Gary,Dunn,Male,Photobug,Business Systems Development Analyst
187,755,7,Janice,Schmidt,Female,Muxo,Nurse
188,761,2,Stephanie,Olson,Female,Rhynoodle,Web Developer IV
189,761,3,Stephanie,Olson,Female,Rhynoodle,Web Developer IV
190,767,6,Jesse,Reynolds,Male,Browseblab,Assistant Media Planner
191,780,6,Sean,Fernandez,Male,Bubblebox,Compensation Analyst
192,783,10,Phyllis,Meyer,Female,Voolia,Information Systems Manager
193,784,6,Thomas,Bennett,Male,Edgepulse,Clinical Specialist
194,787,7,Jessica,Roberts,Female,Riffpath,Mechanical Systems Engineer
195,791,2,Randy,Hart,Male,Innotype,Tax Accountant
196,792,4,Louise,Stephens,Female,LiveZ,Computer Systems Analyst II
197,794,6,Bobby,Peterson,Male,Fivespan,Financial Analyst
198,798,5,Kelly,Taylor,Female,Meejo,Design Engineer
199,799,7,Kathy,Russell,Female,Vimbo,Geologist IV
200,805,8,Peter,Garcia,Male,Gabtune,Cost Accountant
201,810,2,Kathleen,Perry,Female,Aimbu,Design Engineer
202,813,7,Johnny,Walker,Male,Kayveo,Developer II
203,815,6,Barbara,Ruiz,Female,Yadel,Sales Representative
204,816,2,Rebecca,Mendoza,Female,Mybuzz,Web Developer III
205,819,5,Kathryn,Owens,Female,Oyonder,Systems Administrator I
206,827,4,Keith,Price,Male,Gigabox,Food Chemist
207,827,10,Keith,Price,Male,Gigabox,Food Chemist
208,829,6,John,Reyes,Male,Mydo,Web Designer I
209,831,4,Mary,Romero,Female,Agimba,Quality Engineer
210,847,6,Irene,Owens,Female,Yabox,Accountant II
211,850,10,Elizabeth,Diaz,Female,Topiczoom,Speech Pathologist
212,853,3,Deborah,Carpenter,Female,Youspan,Office Assistant I
213,855,4,Mildred,Watson,Female,Yodel,Product Engineer
214,858,5,Judith,Ferguson,Female,Dabfeed,Administrative Assistant III
215,859,7,Evelyn,Hughes,Female,Fivechat,Clinical Specialist
216,861,1,Kenneth,Smith,Male,Latz,Research Assistant III
217,861,5,Kenneth,Smith,Male,Latz,Research Assistant III
218,866,9,Maria,Murray,Female,Thoughtworks,Design Engineer
219,867,10,Mark,Mason,Male,Photofeed,Human Resources Manager
220,869,7,Paul,Carpenter,Male,Feedfire,Project Manager
221,877,10,Harry,Watkins,Male,Zoomdog,Computer Systems Analyst IV
222,883,8,Sarah,Kim,Female,Topicshots,Cost Accountant
223,884,7,Christine,Weaver,Female,Meevee,Data Coordiator
224,888,2,Jimmy,Wright,Male,Npath,Analog Circuit Design manager
225,893,3,Adam,Lynch,Male,Jaloo,Programmer IV
226,905,1,Richard,Fernandez,Male,Shuffletag,Librarian
227,909,6,Cheryl,Davis,Female,Edgeify,Health Coach IV
228,913,2,Ryan,Simmons,Male,Eabox,Senior Financial Analyst
229,919,8,Ronald,Welch,Male,Avamba,Help Desk Technician
230,922,1,Willie,Payne,Male,Devify,Assistant Media Planner
231,922,2,Willie,Payne,Male,Devify,Assistant Media Planner
232,927,4,Nicholas,Morris,Male,Linkbridge,Assistant Professor
233,928,10,Michael,Lopez,Male,Ailane,Nuclear Power Engineer
234,936,9,Matthew,Wagner,Male,Feedspan,Civil Engineer
235,937,10,Sharon,Mcdonald,Female,Eimbee,Recruiting Manager
236,937,2,Sharon,Mcdonald,Female,Eimbee,Recruiting Manager
237,938,10,Steven,Reyes,Male,Jaxnation,Technical Writer
238,940,8,Bonnie,Bowman,Female,Avavee,Internal Auditor
239,942,3,Deborah,Morgan,Female,Browsebug,Tax Accountant
240,945,4,Anne,Reed,Female,Twitterworks,Director of Sales
241,951,5,Angela,Sanders,Female,Dabtype,Research Assistant IV
242,957,10,Shawn,George,Male,Browseblab,GIS Technical Architect
243,959,4,Laura,Ferguson,Female,Pixonyx,Electrical Engineer
244,959,2,Laura,Ferguson,Female,Pixonyx,Electrical Engineer
245,968,4,Teresa,Reynolds,Female,Flashdog,Budget/Accounting Analyst IV
246,969,3,Marie,Ortiz,Female,Meejo,Research Associate
247,977,7,Cynthia,Dixon,Female,Skalith,Automation Specialist II
248,994,2,Clarence,Morgan,Male,Edgewire,Geologist II
249,996,10,Debra,Garcia,Female,Dazzlesphere,Structural Engineer

In [55]:
customers.head()

   ID First Name Last Name  Gender  Company                     Occupation
0   1     Joseph   Perkins    Male  Dynazzy  Community Outreach Specialist
1   2   Jennifer   Alvarez  Female     DabZ        Senior Quality Engineer
2   3      Roger     Black    Male  Tagfeed              Account Executive
3   4     Steven     Evans    Male     Fatz               Registered Nurse
4   5       Judy  Morrison  Female  Demivee                Legal Assistant

In [58]:
week1 = pd.read_csv("/home/gabrielajachs/Downloads/pandas/Restaurant - Week 1 Sales.csv")
pd.set_option('display.max_rows', 50000000)
week2 = pd.read_csv("/home/gabrielajachs/Downloads/pandas/Restaurant - Week 2 Sales.csv")
customers = pd.read_csv("/home/gabrielajachs/Downloads/pandas/Restaurant - Customers.csv", index_col = "ID")
foods = pd.read_csv("/home/gabrielajachs/Downloads/pandas/Restaurant - Foods.csv", index_col = "Food ID")

In [59]:
foods.head()

          Food Item  Price
Food ID
1             Sushi   3.99
2           Burrito   9.99
3              Taco   2.99
4        Quesadilla   4.25
5             Pizza   2.49

In [64]:
sales = week1.merge(customers, how =  "left", left_on = "Customer ID", right_index =  True)
sales = sales.merge(foods, how = "left", left_on = "Food ID", right_index = True)
sales.head()

,Customer ID,Food ID,First Name,Last Name,Gender,Company,Occupation,Food Item,Price
0,537,9,Cheryl,Carroll,Female,Zoombeat,Registered Nurse,Donut,0.99
1,97,4,Amanda,Watkins,Female,Ozu,Account Coordinator,Quesadilla,4.25
2,658,1,Patrick,Webb,Male,Browsebug,Community Outreach Specialist,Sushi,3.99
3,202,2,Louis,Campbell,Male,Rhynoodle,Account Representative III,Burrito,9.99
4,155,9,Carolyn,Diaz,Female,Gigazoom,Database Administrator III,Donut,0.99

In [66]:
week1.merge(week2, how = "left", left_index = True, right_index = True, suffixes = [" - Week 1", " - Week 2"])

,Customer ID - Week 1,Food ID - Week 1,Customer ID - Week 2,Food ID - Week 2
0,537,9,688,10
1,97,4,813,7
2,658,1,495,10
3,202,2,189,5
4,155,9,267,3
5,213,8,310,5
6,600,1,761,2
7,503,5,443,5
8,71,3,729,9
9,174,3,741,8
10,961,9,847,6
11,966,5,156,10
12,641,4,550,7
13,288,2,620,10
14,149,4,272,4
15,954,2,511,2
16,147,9,8,6
17,155,1,534,7
18,550,6,909,6
19,101,7,732,9
20,549,6,372,4
21,75,6,713,1
22,78,7,496,3
23,514,5,381,9
24,833,7,13,2
25,329,8,101,4
26,586,10,325,7
27,341,1,674,2
28,519,10,564,8
29,680,9,578,5
30,419,7,21,4
31,20,1,755,7
32,822,6,509,7
33,226,10,639,2
34,203,2,170,2
35,77,1,668,3
36,628,4,321,3
37,296,9,629,2
38,821,9,767,6
39,697,8,799,7
40,264,7,253,8
41,477,9,473,1
42,524,4,537,5
43,121,3,343,5
44,290,7,761,3
45,100,1,922,1
46,260,6,780,6
47,798,9,198,10
48,462,3,937,10
49,896,7,479,3
50,953,1,706,7
51,682,10,281,6
52,809,7,726,7
53,450,10,343,2
54,772,7,277,3
55,304,3,969,3
56,159,6,543,4
57,189,4,275,8
58,876,2,787,7
59,864,8,424,4
60,799,8,612,6
61,68,6,379,9
62,812,8,647,1
63,30,2,942,3
64,921,2,528,10
65,941,6,673,4
66,108,3,853,3
67,315,4,111,3
68,358,10,736,8
69,249,9,503,8
70,491,9,445,6
71,110,8,580,10
72,737,3,670,6
73,836,6,359,6
74,749,9,132,8
75,758,8,819,5
76,527,3,829,6
77,677,10,928,10
78,741,3,592,5
79,540,3,163,10
80,433,7,694,7
81,250,10,98,5
82,504,1,791,2
83,819,4,398,5
84,910,7,709,4
85,351,10,56,3
86,282,7,397,1
87,117,5,239,6
88,937,10,304,3
89,63,6,893,3
90,144,2,581,1
91,393,7,693,3
92,380,7,827,4
93,515,7,815,6
94,233,3,574,9
95,357,3,752,10
96,3,2,596,8
97,875,2,489,9
98,352,6,792,4
99,93,3,861,1
100,323,1,303,9
101,21,4,548,9
102,64,10,517,2
103,912,10,784,6
104,327,6,621,6
105,399,2,529,10
106,459,6,204,10
107,418,7,136,1
108,669,3,994,2
109,259,9,186,3
110,816,7,253,7
111,761,9,859,7
112,410,7,496,8
113,304,2,423,2
114,772,10,211,4
115,80,2,884,7
116,363,9,81,10
117,504,5,437,10
118,728,6,526,1
119,71,8,951,5
120,479,6,508,4
121,922,1,236,5
122,244,2,127,1
123,319,9,198,7
124,909,1,877,10
125,919,10,816,2
126,51,2,666,9
127,26,9,415,5
128,472,8,24,8
129,77,9,720,1
130,608,6,240,2
131,160,5,919,8
132,645,8,459,1
133,574,10,938,10
134,374,4,46,6
135,100,7,458,9
136,762,8,630,6
137,45,7,75,4
138,332,7,287,5
139,338,10,927,4
140,140,8,522,8
141,567,2,805,8
142,602,1,365,6
143,10,2,257,1
144,77,2,957,10
145,74,1,692,4
146,1000,2,547,10
147,529,7,798,5
148,881,5,913,2
149,673,7,35,8
150,107,2,968,4
151,876,8,222,10
152,703,1,122,2
153,225,10,73,8
154,962,1,653,9
155,114,5,937,2
156,250,7,171,2
157,346,4,193,2
158,191,2,668,9
159,331,2,996,10
160,310,2,222,10
161,738,9,70,2
162,427,7,77,7
163,331,5,743,8
164,902,6,589,4
165,867,9,867,10
166,385,5,831,4
167,555,9,905,1
168,67,7,977,7
169,138,4,746,10
170,775,5,922,2
171,833,3,866,9
172,648,5,746,10
173,475,10,495,6
174,483,6,486,6
175,968,1,55,9
176,203,3,312,2
177,313,9,604,3
178,263,8,122,10
179,871,5,936,9
180,747,5,503,9
181,38,4,628,7
182,190,9,55,4
183,348,6,858,5
184,226,3,175,6
185,167,9,530,7
186,671,8,850,10
187,190,1,681,10
188,909,4,750,6
189,501,6,578,5
190,406,2,287,8
191,47,8,39,10
192,482,3,458,3
193,163,1,30,4
194,991,2,827,10
195,539,6,462,8
196,53,2,361,6
197,51,10,27,4
198,348,9,234,1
199,321,1,570,8
200,493,9,751,2
201,650,9,463,10
202,310,1,253,5
203,848,6,633,1
204,307,9,622,9
205,798,1,959,4
206,606,7,810,2
207,100,4,80,4
208,783,6,155,3
209,985,5,488,2
210,123,6,482,1
211,809,10,495,2
212,21,4,188,8
213,764,9,861,5
214,92,1,305,2
215,386,6,869,7
216,331,3,131,1
217,62,5,520,7
218,91,8,208,4
219,368,6,145,5
220,147,8,495,2
221,745,4,794,6
222,184,3,734,10
223,828,8,540,3
224,578,5,735,2
225,491,4,940,8
226,62,4,571,7
227,77,9,888,2
228,506,9,664,6
229,271,9,343,7
230,584,10,143,4
231,148,5,505,3
232,595,3,54,8
233,274,10,959,2
234,646,1,367,8
235,520,8,883,8
236,644,8,251,9
237,725,8,855,4
238,934,4,233,3
239,151,10,559,10
240,945,5,734,1
241,343,3,677,3
242,380,9,276,4
243,911,4,45,8
244,621,9,945,4
245,413,9,783,10
246,926,6,556,10
247,134,3,547,9
248,396,6,252,9
249,535,10,249,6

In [67]:
week1 = pd.read_csv("/home/gabrielajachs/Downloads/pandas/Restaurant - Week 1 Sales.csv")
pd.set_option('display.max_rows', 50000000)
week2 = pd.read_csv("/home/gabrielajachs/Downloads/pandas/Restaurant - Week 2 Sales.csv")
customers = pd.read_csv("/home/gabrielajachs/Downloads/pandas/Restaurant - Customers.csv")
foods = pd.read_csv("/home/gabrielajachs/Downloads/pandas/Restaurant - Foods.csv")
satisfaction = pd.read_csv("/home/gabrielajachs/Downloads/pandas/Restaurant - Week 1 Satisfaction.csv")

In [68]:
satisfaction

     Satisfaction Rating
0                      2
1                      7
2                      3
3                      7
4                     10
5                      3
6                      2
7                      5
8                     10
9                      7
10                     7
11                     5
12                     3
13                     2
14                     7
15                     4
16                     6
17                     1
18                     5
19                     5
20                     3
21                     2
22                     3
23                    10
24                     4
25                     9
26                     1
27                     4
28                     4
29                     9
30                     8
31                     9
32                     7
33                     1
34                     1
35                     3
36                     3
37                     4
38                     3
39                     9
40                     9
41                     8
42                     8
43                     2
44                     3
45                    10
46                     3
47                     8
48                     6
49                     9
50                     9
51                     3
52                     4
53                     8
54                     8
55                     4
56                    10
57                     4
58                    10
59                     9
60                    10
61                     6
62                     6
63                     5
64                     5
65                     9
66                     9
67                     1
68                     9
69                     6
70                     8
71                     1
72                     8
73                     8
74                     1
75                     8
76                     1
77                     6
78                     2
79                     8
80                     2
81                     2
82                     3
83                     8
84                     4
85                     3
86                     5
87                     1
88                     1
89                     5
90                     3
91                     8
92                     9
93                     2
94                     6
95                     5
96                     7
97                     4
98                     6
99                     4
100                    7
101                    1
102                    2
103                    3
104                    1
105                    9
106                    8
107                    2
108                    5
109                    7
110                   10
111                    6
112                    7
113                    1
114                    7
115                    1
116                    4
117                    9
118                    2
119                    7
120                    5
121                    4
122                    7
123                    4
124                    1
125                    7
126                    4
127                    1
128                    5
129                    4
130                    1
131                    9
132                    5
133                    6
134                    2
135                    2
136                    1
137                    5
138                    9
139                    6
140                    8
141                    3
142                    7
143                   10
144                    3
145                    1
146                    1
147                    5
148                    7
149                    1
150                    6
151                   10
152                    6
153                    4
154                    8
155                    5
156                    4
157                    1
158                    4
159                    3
160                    7
161                    5
162                    9
163                    1
164                    5
165                    7
166                    3
167                    8
168                    6
169                   10
170                    4
171                    5
172                    1
173                    3
174                    1
175                    6
176                    2
177                    4
178                    8
179                    8
180                    9
181                   10
182                   10
183                   10
184                    6
185                   10
186                    4
187                    6
188                    2
189                    3
190                    2
191                    3
192                   10
193                    8
194                    5
195                    1
196                    9
197                    4
198                    5
199                    4
200                    1
201                    9
202                    8
203                    9
204                    8
205                    6
206                    6
207                    5
208                    9
209                    3
210                    5
211                    4
212                    5
213                    1
214                   10
215                    6
216                    3
217                    5
218                    7
219                   10
220                    3
221                    8
222                    4
223                    2
224                    5
225                    2
226                    6
227                    4
228                    9
229                    2
230                    4
231                    8
232                    4
233                    2
234                    9
235                    4
236                    6
237                    6
238                    7
239                   10
240                    8
241                    1
242                    2
243                    8
244                    2
245                    1
246                    2
247                    8
248                   10
249                    3

In [69]:
week1.head()

   Customer ID  Food ID
0          537        9
1           97        4
2          658        1
3          202        2
4          155        9

In [71]:
week1.join(satisfaction).head()

   Customer ID  Food ID  Satisfaction Rating
0          537        9                    2
1           97        4                    7
2          658        1                    3
3          202        2                    7
4          155        9                   10